services:
  - type: web
    name: tds-virtual-ta
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
